### ISSUE TITLE
 this is add in my setting file and give that error

### ISSUE THREAD

**Issue by neerajkumarsingh17** [hoschiCZ/instastories-backup#10]
`Traceback (most recent call last):
  File "./manage.py", line 119, in <module>
    startup = importlib.import_module(edx_args.startup)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/edx/app/edxapp/edx-platform/lms/startup.py", line 9, in <module>
    settings.INSTALLED_APPS  # pylint: disable=pointless-statement
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/edx/app/edxapp/edx-platform/lms/envs/devstack_docker.py", line 3, in <module>
    from .devstack import *  # pylint: disable=wildcard-import, unused-wildcard-import
  File "/edx/app/edxapp/edx-platform/lms/envs/devstack.py", line 8, in <module>
    from .production import *  # pylint: disable=wildcard-import, unused-wildcard-import
  File "/edx/app/edxapp/edx-platform/lms/envs/production.py", line 108, in <module>
    ENV_TOKENS = json.load(env_file)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 44 column 31 (char 1721)

> this is add in my setting file and give that error
"ADDL_INSTALLED_APPS": [ 
        "REGISTRATION_EXTENSION_FORM": "lms.djangoapps.my_login.forms.UserForm" 
    ],
`

**Comment by ondrejsojka** [comment]
Wrong project, closing.

Dne čt 25. 4. 2019 13:00 uživatel neerajkumarsingh17 <
notifications@github.com> napsal:
